#screen
WIDTH1_SCREEN = 350
HEIGHT1_SCREEN = 500
WIDTH2_SCREEN = 700
HEIGHT2_SCREEN = 500
TEXT_FONT1 = 50
TEXT_FONT2 = 40
TEXT_FONT3 = 23
#button start
WIDTH_BUTTON_START = 170
HEIGHT_BUTTON_START = 50
POSX_BUTTON_START = 90
POSY_BUTTON_START = 350
BUTTON_START_SIZE = (WIDTH_BUTTON_START, HEIGHT_BUTTON_START)
BUTTON_START_POS = (POSX_BUTTON_START, POSY_BUTTON_START)
TEXT_BUTTON_START_POS = (120, 360)
#button end
WIDTH_BUTTON_EXIT = 170
HEIGHT_BUTTON_EXIT = 50
POSX_BUTTON_EXIT = 90
POSY_BUTTON_EXIT = 420
BUTTON_EXIT_SIZE = (WIDTH_BUTTON_EXIT, HEIGHT_BUTTON_EXIT)
BUTTON_EXIT_POS = (POSX_BUTTON_EXIT, POSY_BUTTON_EXIT)
TEXT_BUTTON_EXIT_POS = (135, 430)
#box choose input
WIDTH_BOX_INPUT = 300
HEIGHT_BOX_INPUT = 50
POSX_BOX_INPUT = 25
POSY_BOX_INPUT = 20
BOX_INPUT_SIZE = (WIDTH_BOX_INPUT, HEIGHT_BOX_INPUT)
BOX_INPUT_POS = (POSX_BOX_INPUT, POSY_BOX_INPUT)
TEXT_BOX_INPUT_POS = (30, 35)
#box waiting
WIDTH_BOX_WAITING = 200
HEIGHT_BOX_WAITING = 30
POSX_BOX_WAITING = (WIDTH1_SCREEN-WIDTH_BOX_WAITING)/2
POSY_BOX_WAITING = 450
BOX_WAITING_SIZE = (WIDTH_BOX_WAITING, HEIGHT_BOX_WAITING)
BOX_WAITING_POS = (POSX_BOX_WAITING, POSY_BOX_WAITING)
TEXT_BOX_WAITING_POS = (POSX_BOX_WAITING+30, POSY_BOX_WAITING+5)
#box controller
WIDTH_BOX_CONTROLLER = WIDTH2_SCREEN
HEIGHT_BOX_CONTROLLER = 30
POSX_BOX_CONTROLLER = 0
POSY_BOX_CONTROLLER = 0
BOX_CONTROLLER_SIZE = (WIDTH_BOX_CONTROLLER, HEIGHT_BOX_CONTROLLER)
BOX_CONTROLLER_POS = (POSX_BOX_CONTROLLER, POSY_BOX_CONTROLLER)
#back button
BACK_BUTTON_SIZE = (50, 30)
BACK_BUTTON_POS = (0, 0)
#start button
START_BUTTON_SIZE = (40, 30)
START_BUTTON_POS = (80, 0)
#pause button
PAUSE_BUTTON_SIZE = (40, 30)
PAUSE_BUTTON_POS = (130, 0)
#reset button
RESET_BUTTON_SIZE = (40, 30)
RESET_BUTTON_POS = (180, 0)
#dropdown menu
DROPDOWN_WIDTH = 120
DROPDOWN_HEIGHT = 30
DROPDOWN_POSX = WIDTH2_SCREEN - DROPDOWN_WIDTH
DROPDOWN_POSY = 0
#Object
SIDE = (30, 30)
#color
GRAY_BUTTON = (128,128,128,230)
GRAY_BUTTON_DIF = (128,128,128,180)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
WHITE = (255, 255, 255)